name: Tests
on: [push, pull_request]
jobs:
  headless:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Git and Neovim integration
        run: nvim --headless -u NONE -l tests/run.lua
      - name: Native package installation
        run: nvim --headless -u NONE -l tests/install.lua
